version: '3'
services:
  backend:
    build: backend/
    ports: 
      - 3001:3001
    restart: always
    environment:
    - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: always
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - rede-virtual-2
  frontend:
    build: frontend/
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - backend
    volumes:
      - dados-do-banco:/data/db
    networks:
      - rede-virtual-1

volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2: